### ISSUE TITLE
Shown original price is not correct

### ISSUE THREAD

**Issue by ilyassesalama** [FreeStuffBot/discord#23]
This is how the price shows up on Discord:
![image](https://user-images.githubusercontent.com/46769766/147618486-e5c8e4db-7986-435d-afba-78ccee78493e.png)

And this is the price in the Epic Games store:
![image](https://user-images.githubusercontent.com/46769766/147618573-3a48991a-55aa-4f22-aeda-24f648418bb0.png)

**Comment by EasyThe** [comment]
Price differences occur due to the fact that the Epic Games Store doesn't provide a reliable API from which we can fetch the price data. That's why we use Steam for game descriptions, ratings, genres, prices etc.
